//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyCliente
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Banco")]
    public partial class ClienteDC : object
    {
        
        private string Ape_mat_CliField;
        
        private string Ape_pat_CliField;
        
        private string Cod_CliField;
        
        private string Cor_CliField;
        
        private string DepartamentoField;
        
        private string Dir_CliField;
        
        private string DistritoField;
        
        private short EdadField;
        
        private short Est_CliField;
        
        private string EstadoField;
        
        private System.DateTime Fec_RegistroField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private System.DateTime Fec_nac_CliField;
        
        private string Id_UbigeoField;
        
        private string Nom_CliField;
        
        private string Num_doc_CliField;
        
        private string ProvinciaField;
        
        private string Tel_CliField;
        
        private short Tip_doc_CliField;
        
        private string Tipo_DocumentoField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_mat_Cli
        {
            get
            {
                return this.Ape_mat_CliField;
            }
            set
            {
                this.Ape_mat_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_pat_Cli
        {
            get
            {
                return this.Ape_pat_CliField;
            }
            set
            {
                this.Ape_pat_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Cli
        {
            get
            {
                return this.Cod_CliField;
            }
            set
            {
                this.Cod_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cor_Cli
        {
            get
            {
                return this.Cor_CliField;
            }
            set
            {
                this.Cor_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_Cli
        {
            get
            {
                return this.Dir_CliField;
            }
            set
            {
                this.Dir_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Edad
        {
            get
            {
                return this.EdadField;
            }
            set
            {
                this.EdadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_Cli
        {
            get
            {
                return this.Est_CliField;
            }
            set
            {
                this.Est_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_nac_Cli
        {
            get
            {
                return this.Fec_nac_CliField;
            }
            set
            {
                this.Fec_nac_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo
        {
            get
            {
                return this.Id_UbigeoField;
            }
            set
            {
                this.Id_UbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Cli
        {
            get
            {
                return this.Nom_CliField;
            }
            set
            {
                this.Nom_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_doc_Cli
        {
            get
            {
                return this.Num_doc_CliField;
            }
            set
            {
                this.Num_doc_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_Cli
        {
            get
            {
                return this.Tel_CliField;
            }
            set
            {
                this.Tel_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Tip_doc_Cli
        {
            get
            {
                return this.Tip_doc_CliField;
            }
            set
            {
                this.Tip_doc_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_Documento
        {
            get
            {
                return this.Tipo_DocumentoField;
            }
            set
            {
                this.Tipo_DocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        System.Collections.Generic.List<ProxyCliente.ClienteDC> ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCliente.ClienteDC>> ListarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        ProxyCliente.ClienteDC ConsultarCliente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultarClienteAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarClienteDNI", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteDNIResponse")]
        ProxyCliente.ClienteDC ConsultarClienteDNI(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarClienteDNI", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteDNIResponse")]
        System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultarClienteDNIAsync(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        bool InsertarCliente(ProxyCliente.ClienteDC objCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarClienteAsync(ProxyCliente.ClienteDC objCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        bool ActualizarCliente(ProxyCliente.ClienteDC objCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClienteAsync(ProxyCliente.ClienteDC objCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        bool EliminarCliente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarClienteAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioClienteChannel : ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<ProxyCliente.IServicioCliente>, ProxyCliente.IServicioCliente
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioClienteClient() : 
                base(ServicioClienteClient.GetDefaultBinding(), ServicioClienteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioCliente.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), ServicioClienteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyCliente.ClienteDC> ListarCliente()
        {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCliente.ClienteDC>> ListarClienteAsync()
        {
            return base.Channel.ListarClienteAsync();
        }
        
        public ProxyCliente.ClienteDC ConsultarCliente(string strCodigo)
        {
            return base.Channel.ConsultarCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultarClienteAsync(string strCodigo)
        {
            return base.Channel.ConsultarClienteAsync(strCodigo);
        }
        
        public ProxyCliente.ClienteDC ConsultarClienteDNI(string strDNI)
        {
            return base.Channel.ConsultarClienteDNI(strDNI);
        }
        
        public System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultarClienteDNIAsync(string strDNI)
        {
            return base.Channel.ConsultarClienteDNIAsync(strDNI);
        }
        
        public bool InsertarCliente(ProxyCliente.ClienteDC objCliente)
        {
            return base.Channel.InsertarCliente(objCliente);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarClienteAsync(ProxyCliente.ClienteDC objCliente)
        {
            return base.Channel.InsertarClienteAsync(objCliente);
        }
        
        public bool ActualizarCliente(ProxyCliente.ClienteDC objCliente)
        {
            return base.Channel.ActualizarCliente(objCliente);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClienteAsync(ProxyCliente.ClienteDC objCliente)
        {
            return base.Channel.ActualizarClienteAsync(objCliente);
        }
        
        public bool EliminarCliente(string strCodigo)
        {
            return base.Channel.EliminarCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarClienteAsync(string strCodigo)
        {
            return base.Channel.EliminarClienteAsync(strCodigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCliente))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCliente))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Banco/ServicioCliente/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioClienteClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioCliente);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioClienteClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioCliente);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioCliente,
        }
    }
}
