//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Banco
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BancoEntities : DbContext
    {
        public BancoEntities()
            : base("name=BancoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Agencia> Tb_Agencia { get; set; }
        public virtual DbSet<Tb_Cliente> Tb_Cliente { get; set; }
        public virtual DbSet<Tb_Cuenta> Tb_Cuenta { get; set; }
        public virtual DbSet<Tb_Empleado> Tb_Empleado { get; set; }
        public virtual DbSet<Tb_Pago> Tb_Pago { get; set; }
        public virtual DbSet<Tb_Prestamo> Tb_Prestamo { get; set; }
        public virtual DbSet<Tb_Seguro> Tb_Seguro { get; set; }
        public virtual DbSet<Tb_Transferencia> Tb_Transferencia { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<vw_VistaEmpleados> vw_VistaEmpleados { get; set; }
    
        public virtual int usp_ActualizarEmpleado(string cod_Emp, string num_doc_Emp, string tip_doc_Emp, string nom_Emp, string ape_pat_Emp, string ape_mat_Emp, string tel_Emp, string cor_Emp, byte[] img_Emp, string id_Ubigeo, string est_Emp, string usu_Ult_Mod)
        {
            var cod_EmpParameter = cod_Emp != null ?
                new ObjectParameter("Cod_Emp", cod_Emp) :
                new ObjectParameter("Cod_Emp", typeof(string));
    
            var num_doc_EmpParameter = num_doc_Emp != null ?
                new ObjectParameter("Num_doc_Emp", num_doc_Emp) :
                new ObjectParameter("Num_doc_Emp", typeof(string));
    
            var tip_doc_EmpParameter = tip_doc_Emp != null ?
                new ObjectParameter("Tip_doc_Emp", tip_doc_Emp) :
                new ObjectParameter("Tip_doc_Emp", typeof(string));
    
            var nom_EmpParameter = nom_Emp != null ?
                new ObjectParameter("Nom_Emp", nom_Emp) :
                new ObjectParameter("Nom_Emp", typeof(string));
    
            var ape_pat_EmpParameter = ape_pat_Emp != null ?
                new ObjectParameter("Ape_pat_Emp", ape_pat_Emp) :
                new ObjectParameter("Ape_pat_Emp", typeof(string));
    
            var ape_mat_EmpParameter = ape_mat_Emp != null ?
                new ObjectParameter("Ape_mat_Emp", ape_mat_Emp) :
                new ObjectParameter("Ape_mat_Emp", typeof(string));
    
            var tel_EmpParameter = tel_Emp != null ?
                new ObjectParameter("Tel_Emp", tel_Emp) :
                new ObjectParameter("Tel_Emp", typeof(string));
    
            var cor_EmpParameter = cor_Emp != null ?
                new ObjectParameter("Cor_Emp", cor_Emp) :
                new ObjectParameter("Cor_Emp", typeof(string));
    
            var img_EmpParameter = img_Emp != null ?
                new ObjectParameter("Img_Emp", img_Emp) :
                new ObjectParameter("Img_Emp", typeof(byte[]));
    
            var id_UbigeoParameter = id_Ubigeo != null ?
                new ObjectParameter("Id_Ubigeo", id_Ubigeo) :
                new ObjectParameter("Id_Ubigeo", typeof(string));
    
            var est_EmpParameter = est_Emp != null ?
                new ObjectParameter("Est_Emp", est_Emp) :
                new ObjectParameter("Est_Emp", typeof(string));
    
            var usu_Ult_ModParameter = usu_Ult_Mod != null ?
                new ObjectParameter("Usu_Ult_Mod", usu_Ult_Mod) :
                new ObjectParameter("Usu_Ult_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEmpleado", cod_EmpParameter, num_doc_EmpParameter, tip_doc_EmpParameter, nom_EmpParameter, ape_pat_EmpParameter, ape_mat_EmpParameter, tel_EmpParameter, cor_EmpParameter, img_EmpParameter, id_UbigeoParameter, est_EmpParameter, usu_Ult_ModParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEmpleado_Result> usp_ConsultarEmpleado(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEmpleado_Result>("usp_ConsultarEmpleado", codigoParameter);
        }
    
        public virtual int usp_EliminarEmpleado(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEmpleado", codigoParameter);
        }
    
        public virtual int usp_InsertarEmpleado(string num_doc_Emp, string tip_doc_Emp, string nom_Emp, string ape_pat_Emp, string ape_mat_Emp, string tel_Emp, string cor_Emp, byte[] img_Emp, string id_Ubigeo, string est_Emp, string usu_Registro)
        {
            var num_doc_EmpParameter = num_doc_Emp != null ?
                new ObjectParameter("Num_doc_Emp", num_doc_Emp) :
                new ObjectParameter("Num_doc_Emp", typeof(string));
    
            var tip_doc_EmpParameter = tip_doc_Emp != null ?
                new ObjectParameter("Tip_doc_Emp", tip_doc_Emp) :
                new ObjectParameter("Tip_doc_Emp", typeof(string));
    
            var nom_EmpParameter = nom_Emp != null ?
                new ObjectParameter("Nom_Emp", nom_Emp) :
                new ObjectParameter("Nom_Emp", typeof(string));
    
            var ape_pat_EmpParameter = ape_pat_Emp != null ?
                new ObjectParameter("Ape_pat_Emp", ape_pat_Emp) :
                new ObjectParameter("Ape_pat_Emp", typeof(string));
    
            var ape_mat_EmpParameter = ape_mat_Emp != null ?
                new ObjectParameter("Ape_mat_Emp", ape_mat_Emp) :
                new ObjectParameter("Ape_mat_Emp", typeof(string));
    
            var tel_EmpParameter = tel_Emp != null ?
                new ObjectParameter("Tel_Emp", tel_Emp) :
                new ObjectParameter("Tel_Emp", typeof(string));
    
            var cor_EmpParameter = cor_Emp != null ?
                new ObjectParameter("Cor_Emp", cor_Emp) :
                new ObjectParameter("Cor_Emp", typeof(string));
    
            var img_EmpParameter = img_Emp != null ?
                new ObjectParameter("Img_Emp", img_Emp) :
                new ObjectParameter("Img_Emp", typeof(byte[]));
    
            var id_UbigeoParameter = id_Ubigeo != null ?
                new ObjectParameter("Id_Ubigeo", id_Ubigeo) :
                new ObjectParameter("Id_Ubigeo", typeof(string));
    
            var est_EmpParameter = est_Emp != null ?
                new ObjectParameter("Est_Emp", est_Emp) :
                new ObjectParameter("Est_Emp", typeof(string));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEmpleado", num_doc_EmpParameter, tip_doc_EmpParameter, nom_EmpParameter, ape_pat_EmpParameter, ape_mat_EmpParameter, tel_EmpParameter, cor_EmpParameter, img_EmpParameter, id_UbigeoParameter, est_EmpParameter, usu_RegistroParameter);
        }
    
        public virtual ObjectResult<usp_ListarEmpleado_Result> usp_ListarEmpleado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEmpleado_Result>("usp_ListarEmpleado");
        }
    }
}
