//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Cuenta()
        {
            this.Tb_Transferencia = new HashSet<Tb_Transferencia>();
        }
    
        public string Num_Cuen { get; set; }
        public string Tip_Mon { get; set; }
        public Nullable<decimal> Sal_Cuen { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fec_Aper { get; set; }
        public string Cod_Cli { get; set; }
        public string Cod_Age { get; set; }
        public string Est_Cuen { get; set; }
        public string Usu_Registro { get; set; }
        public System.DateTime Fec_Registro { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
    
        public virtual Tb_Agencia Tb_Agencia { get; set; }
        public virtual Tb_Cliente Tb_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Transferencia> Tb_Transferencia { get; set; }
    }
}
