//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Empleado()
        {
            this.Tb_Prestamo = new HashSet<Tb_Prestamo>();
        }
    
        public string Cod_Emp { get; set; }
        public string Num_doc_Emp { get; set; }
        public string Tip_doc_Emp { get; set; }
        public string Nom_Emp { get; set; }
        public string Ape_pat_Emp { get; set; }
        public string Ape_mat_Emp { get; set; }
        public string Tel_Emp { get; set; }
        public string Cor_Emp { get; set; }
        public byte[] Img_Emp { get; set; }
        public string Id_Ubigeo { get; set; }
        public string Est_Emp { get; set; }
        public string Usu_Registro { get; set; }
        public System.DateTime Fec_Registro { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
    
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Prestamo> Tb_Prestamo { get; set; }
    }
}
