//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Prestamo()
        {
            this.Tb_Pago = new HashSet<Tb_Pago>();
        }
    
        public string Cod_Pre { get; set; }
        public decimal Mon_Pre { get; set; }
        public string Cuot_Pre { get; set; }
        public System.DateTime Fec_Sol { get; set; }
        public Nullable<System.DateTime> Fec_Rech { get; set; }
        public Nullable<System.DateTime> Fec_Can { get; set; }
        public int Pre_Est { get; set; }
        public int Com_Deu { get; set; }
        public string Cod_Cli { get; set; }
        public string Cod_Emp { get; set; }
        public string Cod_Age { get; set; }
        public int Est_Pre { get; set; }
        public string Usu_Registro { get; set; }
        public System.DateTime Fec_Registro { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
    
        public virtual Tb_Agencia Tb_Agencia { get; set; }
        public virtual Tb_Cliente Tb_Cliente { get; set; }
        public virtual Tb_Empleado Tb_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Pago> Tb_Pago { get; set; }
    }
}
