//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Pago
    {
        public string Cod_Pag { get; set; }
        public string Num_cuot_Pag { get; set; }
        public decimal Mon_Pag { get; set; }
        public System.DateTime Fec_pro_Pag { get; set; }
        public System.DateTime Fec_real_Pag { get; set; }
        public string Cod_Pre { get; set; }
        public int Est_Pag { get; set; }
        public string Usu_Registro { get; set; }
        public System.DateTime Fec_Registro { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
    
        public virtual Tb_Prestamo Tb_Prestamo { get; set; }
    }
}
