//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Seguro
    {
        public int Cod_Seg { get; set; }
        public decimal Cos_Seg { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fec_Adq { get; set; }
        public string Cod_Cli { get; set; }
    
        public virtual Tb_Cliente Tb_Cliente { get; set; }
    }
}
