//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Usuario
    {
        public string Login_Usuario { get; set; }
        public string Pass_Usuario { get; set; }
        public string Niv_Usuario { get; set; }
        public string Est_Usuario { get; set; }
        public System.DateTime Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
    }
}
