//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyEmpleado
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Banco")]
    public partial class EmpleadoDC : object
    {
        
        private string Ape_mat_EmpField;
        
        private string Ape_pat_EmpField;
        
        private string Cod_EmpField;
        
        private string Cor_EmpField;
        
        private string DepartamentoField;
        
        private string DistritoField;
        
        private short Est_EmpField;
        
        private string EstadoField;
        
        private System.DateTime Fec_RegistroField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private string Id_UbigeoField;
        
        private byte[] Img_EmpField;
        
        private string Nom_EmpField;
        
        private string Num_doc_EmpField;
        
        private string ProvinciaField;
        
        private string Tel_EmpField;
        
        private short Tip_doc_EmpField;
        
        private string Tipo_DocumentoField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_mat_Emp
        {
            get
            {
                return this.Ape_mat_EmpField;
            }
            set
            {
                this.Ape_mat_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_pat_Emp
        {
            get
            {
                return this.Ape_pat_EmpField;
            }
            set
            {
                this.Ape_pat_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Emp
        {
            get
            {
                return this.Cod_EmpField;
            }
            set
            {
                this.Cod_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cor_Emp
        {
            get
            {
                return this.Cor_EmpField;
            }
            set
            {
                this.Cor_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_Emp
        {
            get
            {
                return this.Est_EmpField;
            }
            set
            {
                this.Est_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo
        {
            get
            {
                return this.Id_UbigeoField;
            }
            set
            {
                this.Id_UbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Img_Emp
        {
            get
            {
                return this.Img_EmpField;
            }
            set
            {
                this.Img_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Emp
        {
            get
            {
                return this.Nom_EmpField;
            }
            set
            {
                this.Nom_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_doc_Emp
        {
            get
            {
                return this.Num_doc_EmpField;
            }
            set
            {
                this.Num_doc_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_Emp
        {
            get
            {
                return this.Tel_EmpField;
            }
            set
            {
                this.Tel_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Tip_doc_Emp
        {
            get
            {
                return this.Tip_doc_EmpField;
            }
            set
            {
                this.Tip_doc_EmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_Documento
        {
            get
            {
                return this.Tipo_DocumentoField;
            }
            set
            {
                this.Tipo_DocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEmpleado.IServicioEmpleado")]
    public interface IServicioEmpleado
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ListarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ListarEmpleadoResponse")]
        System.Collections.Generic.List<ProxyEmpleado.EmpleadoDC> ListarEmpleado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ListarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ListarEmpleadoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyEmpleado.EmpleadoDC>> ListarEmpleadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ConsultarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ConsultarEmpleadoResponse")]
        ProxyEmpleado.EmpleadoDC ConsultarEmpleado(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ConsultarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ConsultarEmpleadoResponse")]
        System.Threading.Tasks.Task<ProxyEmpleado.EmpleadoDC> ConsultarEmpleadoAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/InsertarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/InsertarEmpleadoResponse")]
        bool InsertarEmpleado(ProxyEmpleado.EmpleadoDC objEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/InsertarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/InsertarEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> InsertarEmpleadoAsync(ProxyEmpleado.EmpleadoDC objEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ActualizarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ActualizarEmpleadoResponse")]
        bool ActualizarEmpleado(ProxyEmpleado.EmpleadoDC objEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/ActualizarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/ActualizarEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEmpleadoAsync(ProxyEmpleado.EmpleadoDC objEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/EliminarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/EliminarEmpleadoResponse")]
        bool EliminarEmpleado(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpleado/EliminarEmpleado", ReplyAction="http://tempuri.org/IServicioEmpleado/EliminarEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> EliminarEmpleadoAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioEmpleadoChannel : ProxyEmpleado.IServicioEmpleado, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioEmpleadoClient : System.ServiceModel.ClientBase<ProxyEmpleado.IServicioEmpleado>, ProxyEmpleado.IServicioEmpleado
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioEmpleadoClient() : 
                base(ServicioEmpleadoClient.GetDefaultBinding(), ServicioEmpleadoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioEmpleado.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEmpleadoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioEmpleadoClient.GetBindingForEndpoint(endpointConfiguration), ServicioEmpleadoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEmpleadoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioEmpleadoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEmpleadoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioEmpleadoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyEmpleado.EmpleadoDC> ListarEmpleado()
        {
            return base.Channel.ListarEmpleado();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyEmpleado.EmpleadoDC>> ListarEmpleadoAsync()
        {
            return base.Channel.ListarEmpleadoAsync();
        }
        
        public ProxyEmpleado.EmpleadoDC ConsultarEmpleado(string strCodigo)
        {
            return base.Channel.ConsultarEmpleado(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyEmpleado.EmpleadoDC> ConsultarEmpleadoAsync(string strCodigo)
        {
            return base.Channel.ConsultarEmpleadoAsync(strCodigo);
        }
        
        public bool InsertarEmpleado(ProxyEmpleado.EmpleadoDC objEmpleado)
        {
            return base.Channel.InsertarEmpleado(objEmpleado);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarEmpleadoAsync(ProxyEmpleado.EmpleadoDC objEmpleado)
        {
            return base.Channel.InsertarEmpleadoAsync(objEmpleado);
        }
        
        public bool ActualizarEmpleado(ProxyEmpleado.EmpleadoDC objEmpleado)
        {
            return base.Channel.ActualizarEmpleado(objEmpleado);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEmpleadoAsync(ProxyEmpleado.EmpleadoDC objEmpleado)
        {
            return base.Channel.ActualizarEmpleadoAsync(objEmpleado);
        }
        
        public bool EliminarEmpleado(string strCodigo)
        {
            return base.Channel.EliminarEmpleado(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarEmpleadoAsync(string strCodigo)
        {
            return base.Channel.EliminarEmpleadoAsync(strCodigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEmpleado))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEmpleado))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Banco/ServicioEmpleado/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioEmpleadoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioEmpleado);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioEmpleadoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioEmpleado);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioEmpleado,
        }
    }
}
